### ISSUE TITLE
Install develop on Cheyenne with GNU 10 - ESMF errror

### ISSUE THREAD

**Issue by climbfuji** [NOAA-EMC/hpc-stack#201]
**Describe the bug**
This is the second of several issues I am going to create wrt installing hpc-stack develop on Cheyenne.

This time I believe it is specific to the compiler choice GNU 10.1.0 (or any gfortran >=10). Installing ESMF fails with:
```
......
  515 |             call mpi_recv  ( hs, 1, MPI_INTEGER, root, mtag, comm, &
      |                             2
Error: Type mismatch between actual argument at (1) and actual argument at (2) (INTEGER(8)/INTEGER(4)).
/glade/work/heinzell/fv3/hpc-stack-cheyenne-gnu-10.1.0/src/hpc-stack-cheyenne-10/pkg/ESMF_8_1_0_beta_snapshot_27/src/Infrastructure/IO/PIO/pio_support.F90:222:27:

  222 |              call MPI_SEND(dof,int(sdof),PIO_OFFSET_KIND,masterproc,n,comm,ierr)
      |                           1
......
  496 |                   call mpi_send ( hs, 1, MPI_INTEGER, p, mtag, comm, ier )
      |                                  2
Error: Type mismatch between actual argument at (1) and actual argument at (2) (INTEGER(8)/INTEGER(4)).
/glade/work/heinzell/fv3/hpc-stack-cheyenne-gnu-10.1.0/src/hpc-stack-cheyenne-10/pkg/ESMF_8_1_0_beta_snapshot_27/build/common.mk:3863: recipe for target '/glade/work/heinzell/fv3/hpc-stack-cheyenne-gnu-10.1.0/src/hpc-stack-cheyenne-10/pkg/ESMF_8_1_0_beta_snapshot_27/obj/objO/Linux.gfortran.64.mpt.default/pio_support.o' failed
```
I think what is needed are the gfortran-20 compatibility flags that have already been added to the NCEPLIBS, etc.

**To Reproduce**
See https://github.com/NOAA-EMC/hpc-stack/issues/200, but change `config/config_cheyenne_gnu.sh` so that the compiler module is `gnu/10.1.0`.

**Expected behavior**
No errors during installation of cdo.

**System:**
Cheyenne with GNU-10.1.0

**Comment by climbfuji** [comment]
I previously said this is a pio error, but it is not - it's ESMF.

**Comment by aerorahul** [comment]
you can add `export STACK_FFLAGS="-fallow-argument-mismatch"` to the config file when using `gfortran-10` to effect these `FFLAGS` for all packages.

**Comment by climbfuji** [comment]
> you can add `export STACK_FFLAGS="-fallow-argument-mismatch"` to the config file when using `gfortran-10` to effect these `FFLAGS` for all packages.

Of course, but shouldn't we make it such that the stack build sets this automatically when detecting gfortran >= 10 ?

**Comment by aerorahul** [comment]
Sure. That will require going to each `build_package.sh` and add `if-then-else` blocks for `gfortran-10`.
It should be done at some time.
Not sure, how that is any different in effect than adding a single `if-then-else` block in the `config_platform.sh` file.
Plus, it is extremely efficient.

**Comment by climbfuji** [comment]
> Sure. That will require going to each `build_package.sh` and add `if-then-else` blocks for `gfortran-10`.
> It should be done at some time.
> Not sure, how that is any different in effect than adding a single `if-then-else` block in the `config_platform.sh` file.
> Plus, it is extremely efficient.

I hear you. What really needs to be done is to fix the software, not the stack. I will create an issue in ESMF at least, and in the meanwhile add the flags in the Cheyenne config. However, what I would prefer is to add them explicitly for each package (in `config/config_cheyenne_gnu.sh`, no problem) so that we are aware of which packages have problems and not just put a blanket over it.

**Comment by aerorahul** [comment]
Two thumbs up to fixing the issue in the software.

A blanket flag is not ideal, I agree.
We can start identifying which packages are an issue.  ESMF clearly is.

An easy way to do so without messing with all the build scripts is by adding:

```
export STACK_<package>_FFLAGS=-fallow-argument-mismatch
```

in the `config.sh` file.

Or, a more tedious way is to add the following in in each package section of the YAML:
```
    FFLAGS: "-fallow-argument-mismatch"
```

Note: this is just to identify which package needs these.

**Comment by climbfuji** [comment]
I added this to `config/config_cheyenne_gnu.sh`:
```
# gfortran-10 compatibility flags for faulty software
export STACK_esmf_FFLAGS="-fallow-argument-mismatch"
```
But now it fails in the final linker step in during `make install`:
```
mpif90    -m64 -mcmodel=small -pthread -Wl,--no-as-needed  -fopenmp -L/glade/work/heinzell/fv3/hpc-stack-cheyenne-gnu-10.1.0/gnu-10.1.0/mpt-2.22/hdf5/1.10.6/lib   -L/glade/work/heinzell/fv3/hpc-stack-cheyenne-gnu-10.1.0/gnu-10.1.0/zlib/1.2.11/lib -L/glade/work/heinzell/fv3/hpc-stack-cheyenne-gnu-10.1.0/gnu-10.1.0/mpt-2.22/esmf/8_1_0_beta_snapshot_27/lib -L/glade/work/heinzell/fv3/hpc-stack-cheyenne-gnu-10.1.0/gnu-10.1.0/mpt-2.22/netcdf/4.7.4/lib -L/glade/u/apps/ch/opt/gnu/10.1.0/lib/gcc/x86_64-pc-linux-gnu/10.1.0/../../../../lib64/ -Wl,-rpath,/glade/work/heinzell/fv3/hpc-stack-cheyenne-gnu-10.1.0/gnu-10.1.0/mpt-2.22/esmf/8_1_0_beta_snapshot_27/lib -Wl,-rpath,/glade/work/heinzell/fv3/hpc-stack-cheyenne-gnu-10.1.0/gnu-10.1.0/mpt-2.22/netcdf/4.7.4/lib -Wl,-rpath,/glade/u/apps/ch/opt/gnu/10.1.0/lib/gcc/x86_64-pc-linux-gnu/10.1.0/../../../../lib64/ -o /glade/work/heinzell/fv3/hpc-stack-cheyenne-gnu-10.1.0/gnu-10.1.0/mpt-2.22/esmf/8_1_0_beta_snapshot_27/bin/ESMF_Info /glade/work/heinzell/fv3/hpc-stack-cheyenne-gnu-10.1.0/src/hpc-stack-cheyenne-10/pkg/ESMF_8_1_0_beta_snapshot_27/obj/objO/Linux.gfortran.64.mpt.default/src/apps/ESMF_Info/ESMF_Info.o -lesmf  -lmpi++ -lrt -lstdc++ -ldl -lnetcdff -lnetcdf -lhdf5_hl -lhdf5  -lz -ldl -lm
/usr/bin/ld: /glade/work/heinzell/fv3/hpc-stack-cheyenne-gnu-10.1.0/gnu-10.1.0/mpt-2.22/esmf/8_1_0_beta_snapshot_27/lib/libesmf.a(ESMC_InfoCDefGeneric.o): in function `ESMC_InfoGetArrayLG':
/glade/work/heinzell/fv3/hpc-stack-cheyenne-gnu-10.1.0/src/hpc-stack-cheyenne-10/pkg/ESMF_8_1_0_beta_snapshot_27/src/Infrastructure/Base/src/ESMC_InfoCDefGeneric.C:312: undefined reference to `void ESMCI::check_overflow<bool, nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer> >(bool, nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer>)'
/usr/bin/ld: /glade/work/heinzell/fv3/hpc-stack-cheyenne-gnu-10.1.0/gnu-10.1.0/mpt-2.22/esmf/8_1_0_beta_snapshot_27/lib/libesmf.a(ESMC_InfoCDefGeneric.o): in function `ESMC_InfoGetArrayI4':
/glade/work/heinzell/fv3/hpc-stack-cheyenne-gnu-10.1.0/src/hpc-stack-cheyenne-10/pkg/ESMF_8_1_0_beta_snapshot_27/src/Infrastructure/Base/src/ESMC_InfoCDefGeneric.C:232: undefined reference to `void ESMCI::check_overflow<int, nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer> >(int, nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer>)'
/usr/bin/ld: /glade/work/heinzell/fv3/hpc-stack-cheyenne-gnu-10.1.0/gnu-10.1.0/mpt-2.22/esmf/8_1_0_beta_snapshot_27/lib/libesmf.a(ESMC_InfoCDefGeneric.o): in function `ESMC_InfoGetArrayR4':
/glade/work/heinzell/fv3/hpc-stack-cheyenne-gnu-10.1.0/src/hpc-stack-cheyenne-10/pkg/ESMF_8_1_0_beta_snapshot_27/src/Infrastructure/Base/src/ESMC_InfoCDefGeneric.C:152: undefined reference to `void ESMCI::check_overflow<float, nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer> >(float, nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer>)'
/usr/bin/ld: /glade/work/heinzell/fv3/hpc-stack-cheyenne-gnu-10.1.0/gnu-10.1.0/mpt-2.22/esmf/8_1_0_beta_snapshot_27/lib/libesmf.a(ESMC_InfoCDefGeneric.o): in function `ESMC_InfoGetArrayR8':
/glade/work/heinzell/fv3/hpc-stack-cheyenne-gnu-10.1.0/src/hpc-stack-cheyenne-10/pkg/ESMF_8_1_0_beta_snapshot_27/src/Infrastructure/Base/src/ESMC_InfoCDefGeneric.C:192: undefined reference to `void ESMCI::check_overflow<double, nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer> >(double, nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer>)'
/usr/bin/ld: /glade/work/heinzell/fv3/hpc-stack-cheyenne-gnu-10.1.0/gnu-10.1.0/mpt-2.22/esmf/8_1_0_beta_snapshot_27/lib/libesmf.a(ESMC_InfoCDefGeneric.o): in function `ESMC_InfoGetArrayI8':
/glade/work/heinzell/fv3/hpc-stack-cheyenne-gnu-10.1.0/src/hpc-stack-cheyenne-10/pkg/ESMF_8_1_0_beta_snapshot_27/src/Infrastructure/Base/src/ESMC_InfoCDefGeneric.C:272: undefined reference to `void ESMCI::check_overflow<long, nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer> >(long, nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer>)'
collect2: error: ld returned 1 exit status
/glade/work/heinzell/fv3/hpc-stack-cheyenne-gnu-10.1.0/src/hpc-stack-cheyenne-10/pkg/ESMF_8_1_0_beta_snapshot_27/build/common.mk:2429: recipe for target '/glade/work/heinzell/fv3/hpc-stack-cheyenne-gnu-10.1.0/gnu-10.1.0/mpt-2.22/esmf/8_1_0_beta_snapshot_27/bin/ESMF_Info' failed
```

**Comment by aerorahul** [comment]
Sorry for the stupid question, but does ESMF team support building ESMF with GNU 10?

**Comment by climbfuji** [comment]
Well, we do build it successfully in nceplibs-external with gnu-10, this was part of the SRW App release (i.e. branches ufs-v2.0.0 for NCEPLIBS-external and NCEPLIBS).

**Comment by climbfuji** [comment]
A quick update: this is a problem with the later ESMF versions and gnu-10. ESMF 8.0.0 compiles fine with gnu-10.1.0, I tested it using the same code that failed for ESMF 8.1.0 bs27.

**Comment by edwardhartnett** [comment]
FWIW I just sent an email to ESMF support asking them whether they support GNU 10. I will post their answer here...

**Comment by aerorahul** [comment]
> A quick update: this is a problem with the later ESMF versions and gnu-10. ESMF 8.0.0 compiles fine with gnu-10.1.0, I tested it using the same code that failed for ESMF 8.1.0 bs27.

phew! Thanks for the update @climbfuji 
I am glad this is not a problem with the stack.

**Comment by climbfuji** [comment]
Turns out it is a bug in hpc-stack after all. Will create a PR to get ESMF working with GNU 10 soon. EDIT: bit of a gray zone who to blame really. ESMF is not picking up default `FFLAGS` and `CXXFLAGS`, one has to add that explicitly to `ESMF_F90COMPILEOPTS` etc.

**Comment by aerorahul** [comment]
@climbfuji Can this be closed now that #202 is merged?

**Comment by climbfuji** [comment]
Closed via https://github.com/NOAA-EMC/hpc-stack/pull/202.
