### ISSUE TITLE
The GSI fails to compile using wrf_io/1.1.1 from hpc/1.1.0

### ISSUE THREAD

**Issue by MichaelLueken** [NOAA-EMC/hpc-stack#203]
**Describe the bug**
While compiling the GSI using wrf_io/1.1.1 from hpc/1.1.0, the GSI fails with the following:

../../lib/libgsilib_wrf.a(cplr_wrf_binary_interface.f90.o): In function `get_wrf_binary_interface_mod_mp_inventory_wrf_binary_file_':
cplr_wrf_binary_interface.f90:(.text+0x2600e): undefined reference to `wrf_sizeof_integer_'
../../lib/libgsilib_wrf.a(cplr_wrf_binary_interface.f90.o): In function `get_wrf_binary_interface_mod_mp_int_get_ti_header_char_':
cplr_wrf_binary_interface.f90:(.text+0x28976): undefined reference to `int_get_ti_header_c_'

Please add module_machine.F90, io_int_stubs.f90, and pack_utils.c from:

https://vlab.ncep.noaa.gov/redmine/projects/comgsi-external-libs/repository/revisions/master/show/wrflib

so that the GSI can compile using NCEPLIBS-wrf_io.

**To Reproduce**

1) Add module load wrf_io/1.1.1 to modulefiles/modulefile.ProdGSI.$machine (this affects all machines, so add to the modulefile for the machine you are using)

2) Replace the WRF section in CMakeLists.txt with find_package( wrf_io )

3) Attempt to compile

**Expected behavior**
The GSI should be able to compile using wrf_io/1.1.1 from hpc/1.1.0.  This will allow the GSI to remove the libsrc submodule from the authoritative repo, making the GSI more readily available to external developers.

**System:**
This is an issue on all systems.

**Comment by aerorahul** [comment]
@MichaelLueken-NOAA 
Thanks for bringing this up.
Since the GSI housed its own version of `wrf_io`, could you open an issue and PR in the [NCEPLIBS-wrfio](https://github.com/NOAA-EMC/NCEPLIBS-wrf_io) with the necessary changes that works for the GSI.  Otherwise, we might  end up iterating.

**Comment by MichaelLueken** [comment]
@aerorahul
The GSI version should have been the version used in NCEPLIBS-wrfio.  Mark Potts created the GSI's libsrc/wrflib version long before the NCEPLIBS version.  Why didn't NCEPLIBS start with Mark's work to ensure that all necessary components for the GSI were included?  The NCEPLIBS group will need to correct this.  I will be more than willing to test the version to ensure that it works with the GSI.

**Comment by aerorahul** [comment]
@MichaelLueken-NOAA 
hpc-stack installs the package, and does not maintain the packages it installs.
It is not in the scope of hpc-stack to make code changes in these packages.

This is a bug or missing feature in NCEPLIBS-wrf_io.
Please open an issue there so that the appropriate person/group will take action.  

Once the proper code is in place in NCEPLIBS-wrf_io, please open an issue in hpc-stack indicating the tag of NCEPLIBS-wrf_io, that needs to be installed via the stack. It will have to be tested with other applications that use wrf_io; e.g. EMC_post.

**Comment by edwardhartnett** [comment]
I have added an issue to NCEPLIBS-wrf_io.

When there is a new version of NCEPLIBS-wrf_io, we can upgrade the version in hpc-stack.

**Comment by GeorgeVandenberghe-NOAA** [comment]
I have to make sure the post API and the GSI API are compatible.  Otherwise they will have to be made so with communications from both post and GSI  people (worst case).   The WRF API itself is not stable and changes from major release to major release

**Comment by kgerheiser** [comment]
This has been fixed with #246
