### ISSUE TITLE
ESMF v8.4.0b08

### ISSUE THREAD

**Issue by DusanJovic-NOAA** [NOAA-EMC/hpc-stack#481]
Note: Please search to see if an issue already exists for the software you are requesting to be installed.

**Which software in the stack would you like installed?**
Please provide the name of the software you would like installed on the HPCs.  Ensure the software exists in the list of supported software.  If new software needs to be added to the stack, use the [add_package_request.md](./add_package_request.md) template.

ESMF

**What is the version/tag of the software?**
Please provide the version/tag of the software to be installed.
8.4.0b08 https://github.com/esmf-org/esmf/releases/tag/v8.4.0b08

**What compilation options would you like set?**
Give a detailed list of compilation options, compiler and MPI flavors and versions, etc.
Same options as current ESMF versions

**Which machines would you like to have the software installed?**
See currently managed HPC machines.
Initially Hera/Intel

**Any other relevant information that we should know to correctly install the software??**
Please describe in as much detail as possible.

**Additional context**
Add any other context or screenshots about the install request here.

**Comment by kgerheiser** [comment]
Working on this now

**Comment by Hang-Lei-NOAA** [comment]
It has been on Hera, except for an error with the gnu compiler. It is under
debugging.

**Comment by kgerheiser** [comment]
Done on Orion, Jet and Gaea.

**Comment by DusanJovic-NOAA** [comment]
Trying to build ufs on Hera:
```
Lmod has detected the following error: Cannot load module                                                                            
"mapl/2.22.0-esmf-8.3.0b09". At least one of these module(s) must be loaded:                                                         
   esmf/8.3.0b09 esmf/8.3.0b09-debug                                                                                                 
                                                                                                                                     
While processing the following module(s):                                                                                            
    Module fullname            Module Filename                                                                                       
    ---------------            ---------------                                                                                       
    mapl/2.22.0-esmf-8.3.0b09  /scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/modulefiles/mpi/intel/2022.1.2/impi/2022.1.2/mapl/2.22.0-esmf-8.3.0b09.lua
    ufs_common                 /scratch2/NCEPDEV/fv3-cam/Dusan.Jovic/ufs/missing_value_r4/ufs-weather-model/modulefiles/ufs_common   
    ufs_hera.intel             /scratch2/NCEPDEV/fv3-cam/Dusan.Jovic/ufs/missing_value_r4/ufs-weather-model/modulefiles/ufs_hera.intel
```
We need mapl build with v8.4.0b08. I wonder if this is really necessary or mapl module just requires exact esmf version?

**Comment by Hang-Lei-NOAA** [comment]
I will add mapl/2.22.0 with 8.4.0b08

**Comment by kgerheiser** [comment]
The MAPL module requires exact ESMF version. Maybe not necessary, but sometimes it can cause subtle bugs if there's an API change or something like that. It happened once before and since then we've kept them in lockstep.

**Comment by Hang-Lei-NOAA** [comment]
mapl/2.22.0-esmf-8.4.0b08 is added on Hera

**Comment by DusanJovic-NOAA** [comment]
I'm getting compile (link) errors:
```
/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-2022.1.2/impi-2022.1.2/pio/2.5.3/lib/libpioc.a(pioc.c.o): In function `PIOc_iosystem_is_active':
/scratch2/NCEPDEV/nwprod/hpc-stack/src/develop/pkg/pio-2.5.3/src/clib/pioc.c:95: multiple definition of `PIOc_iosystem_is_active'
/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-2022.1.2/impi-2022.1.2/esmf/8.4.0b08/lib/libpioc.a(pioc.c.o):/scratch2/NCEPDEV/nwprod/hpc-stack/src/v1.2.0/pkg/
v8.4.0b08/src/Infrastructure/IO/PIO/ParallelIO/src/clib/pioc.c:97: first defined here
/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-2022.1.2/impi-2022.1.2/pio/2.5.3/lib/libpioc.a(pioc.c.o): In function `PIOc_File_is_Open':
/scratch2/NCEPDEV/nwprod/hpc-stack/src/develop/pkg/pio-2.5.3/src/clib/pioc.c:109: multiple definition of `PIOc_File_is_Open'
/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-2022.1.2/impi-2022.1.2/esmf/8.4.0b08/lib/libpioc.a(pioc.c.o):/scratch2/NCEPDEV/nwprod/hpc-stack/src/v1.2.0/pkg/
v8.4.0b08/src/Infrastructure/IO/PIO/ParallelIO/src/clib/pioc.c:111: first defined here
/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-2022.1.2/impi-2022.1.2/pio/2.5.3/lib/libpioc.a(pioc.c.o): In function `PIOc_advanceframe':
```

**Comment by kgerheiser** [comment]
Ah, ESMF 8.3.0 changed the PIO option. It now supports using an external PIO with version > 2.5.7.

**Comment by Hang-Lei-NOAA** [comment]
@Kyle Gerheiser - NOAA Affiliate ***@***.***> we have to
install the pio/2.5.7 and then rebuild it?

**Comment by kgerheiser** [comment]
Maybe, and also update a build setting. I haven't looked into it too deeply yet, but that's a change that I remember in ESMF 8.3.0 that wasn't in v8.3.0b09.

**Comment by Hang-Lei-NOAA** [comment]
@Kyle Gerheiser - NOAA Affiliate ***@***.***> Thanks, I am
trying to update the installation with compiler intel/2022.1 and let Dusan
test it if it works. I used the latest PIO/2.5.8.

**Comment by kgerheiser** [comment]
I think there's more to it than that. The option that's passed to ESMF in the build needs to be updated too.

**Comment by Hang-Lei-NOAA** [comment]
@Kyle Gerheiser - NOAA Affiliate ***@***.***> Thanks, I will
study the details from ESMF changes.

**Comment by kgerheiser** [comment]
I see what's going on now. The internal ESMF PIO is conflicting with the external PIO. We should set ESMF to use an external PIO for consistency.

**Comment by Hang-Lei-NOAA** [comment]
@Dusan Jovic - NOAA Affiliate ***@***.***> Could you please test
the intel/2022.1 build with PIO/2.5.8 and let me know the result?
The ESMF user guide said that miniversion for PIO is 2.5.7.

**Comment by DusanJovic-NOAA** [comment]
UFS WM compiled successfully using pio/2.5.8. Please install debug versions of esmf and mapl.

**Comment by DusanJovic-NOAA** [comment]
> UFS WM compiled successfully using pio/2.5.8. Please install debug versions of esmf and mapl.

I see debug version of esmf, already installed. Thanks.

**Comment by kgerheiser** [comment]
@Hang-Lei-NOAA I think we should use PIO 2.5.7 because 2.5.8 doesn't have an actual release yet https://github.com/NCAR/ParallelIO/releases, it matches the version in ESMF, and it matches the version that we're building in Spack.

**Comment by Hang-Lei-NOAA** [comment]
@Kyle Gerheiser - NOAA Affiliate ***@***.***> Okay, I will use
it. In addition, in the coming a few days, I am planning to use your spack
to install the libraries on Acorn. So that the transition can be smooth
with your help.

**Comment by junwang-noaa** [comment]
@Hang-Lei-NOAA @edwardhartnett @AlexanderRichert-NOAA I'd like to follow up with this issue. Since ESMF v8.4.0 release is out last year, can we install ESMF 8.4.0 release, instead of the beta snapshot version. I'd like to bring this up with high priority as several projects including WAM, HAFSv1 need this version for operational implementation. 

@BrianCurtis-NOAA FYI.

**Comment by Hang-Lei-NOAA** [comment]
Hi, Jun

I have built the esmf/8.4.0 and mapl/2.23.1 based on system installed libs
on Cactus and Acorn.
On Cactus:
It is on:
/lfs/h2/emc/eib/save/hang.lei/forgdit/nco_wcoss2/install/modulefiles/mpi/intel/19.1.3.304/cray-mpich/8.1.9

The test loading example is under this UFS folder:
/lfs/h2/emc/eib/noscrub/hang.lei/testufs/modulefiles/ufs_wcoss2.intel.lua.back

ESMF use internal PIO set.

Acorn is:
/lfs/h1/emc/nceplibs/noscrub/Hang.Lei/works/libs

module use
/lfs/h1/emc/nceplibs/noscrub/Hang.Lei/works/libs/modulefiles/mpi/intel/19.1.3.304/cray-mpich/8.1.9
module load esmf/8.4.0
module load mapl/2.23.1-esmf-8.4.0

======================
hdf/1.12.2
netcdf/4.9.0
ecbuild/3.7.0  gftl_shared/1.5.0  yafyaml/1.0.4 (Curtis build)

Thanks,
Hang

**Comment by aerorahul** [comment]
Seems like this is also done. 
Closing. 
Reopen if still relevant.
